from __future__ import annotations

import json
from pathlib import Path
from typing import Any


def write_portable_exports(context: dict[str, Any], output_dir: Path) -> list[Path]:
    output_dir.mkdir(parents=True, exist_ok=True)
    markdown = render_context_markdown(context)
    serialized_json = json.dumps(context, indent=2, ensure_ascii=True) + "\n"
    paths = [
        output_dir / "UACL_CONTEXT.md",
        output_dir / "uacl-context.json",
        output_dir / "AI_CONTEXT.md",
        output_dir / "project-context.json",
    ]

    for path in paths:
        content = serialized_json if path.suffix == ".json" else markdown
        path.write_text(content, encoding="utf-8")
    return paths


def render_context_markdown(context: dict[str, Any]) -> str:
    project = context.get("project", {})
    architecture = context.get("architecture", {})
    navigation = context.get("navigation_map", {})

    sections = [
        f"# UACL Context: {project.get('name', 'Unnamed project')}",
        "",
        "> Portable, model-independent project context for AI assistants and agents.",
        "> Treat this file as a shared source of truth across tools and workflows.",
        "",
        "## Project Summary",
        "",
        project.get("summary") or "No project summary recorded.",
        "",
        "## Project Goals",
        "",
        _bullet_list(context.get("project_goals", [])),
        "",
        "## Tech Stack",
        "",
        _bullet_list(
            context.get("tech_stack", []) or project.get("detected_languages", [])
        ),
        "",
        "## Architecture",
        "",
        "### Layers",
        "",
        _mapping_list(architecture.get("layers", []), "name", "role"),
        "",
        "### Entry Points",
        "",
        _path_list(architecture.get("entry_points", [])),
        "",
        "### Important Files",
        "",
        _path_list(navigation.get("key_files", [])),
        "",
        "## Current Tasks",
        "",
        _bullet_list(context.get("current_tasks", [])),
        "",
        "## Decisions",
        "",
        _decision_list(context.get("decisions", [])),
        "",
        "## Constraints",
        "",
        _bullet_list(context.get("constraints", [])),
        "",
        "## Known Issues",
        "",
        _bullet_list(context.get("known_issues", [])),
        "",
        "## AI Instructions",
        "",
        _bullet_list(context.get("ai_instructions", [])),
        "",
        "## Agent Roles",
        "",
        _mapping_list(context.get("agent_roles", []), "name", "responsibility"),
        "",
        "## Task Routes",
        "",
        _task_routes(context.get("task_routes", {})),
        "",
        "## Context Metadata",
        "",
        f"- UACL schema version: `{context.get('uacl_version', context.get('aicontext_version', 'unknown'))}`",
        "- Canonical context map: `.ai/context.yaml`",
        "- Generated by: Universal AI Context Layer (UACL)",
        "",
    ]
    return "\n".join(sections)


def _bullet_list(items: list[Any]) -> str:
    return "\n".join(f"- {item}" for item in items) if items else "- None recorded."


def _path_list(items: list[dict[str, Any]]) -> str:
    if not items:
        return "- None recorded."
    lines = []
    for item in items:
        detail = (
            item.get("role")
            or item.get("importance")
            or ", ".join(item.get("reasons", []))
        )
        suffix = f": {detail}" if detail else ""
        lines.append(f"- `{item.get('path', 'unknown')}`{suffix}")
    return "\n".join(lines)


def _mapping_list(items: list[dict[str, Any]], name_key: str, detail_key: str) -> str:
    if not items:
        return "- None recorded."
    return "\n".join(
        f"- **{item.get(name_key, 'Unnamed')}**: {item.get(detail_key, 'Not recorded.')}"
        for item in items
    )


def _decision_list(items: list[Any]) -> str:
    if not items:
        return "- None recorded."
    lines = []
    for item in items:
        if isinstance(item, dict):
            title = item.get("title") or item.get("decision") or "Decision"
            rationale = (
                item.get("rationale") or item.get("reason") or "No rationale recorded."
            )
            lines.append(f"- **{title}**: {rationale}")
        else:
            lines.append(f"- {item}")
    return "\n".join(lines)


def _task_routes(routes: dict[str, list[dict[str, Any]]]) -> str:
    if not routes:
        return "- None recorded."
    lines = []
    for category, items in routes.items():
        paths = ", ".join(f"`{item['path']}`" for item in items[:5])
        lines.append(f"- **{category}**: {paths or 'None recorded.'}")
    return "\n".join(lines)
